compile_pdf:
  stage: build
  image: timnn/texlive
  script: 
#    - pdflatex -interaction=batchmode main.tex
    - pdflatex -interaction=nonstopmode -halt-on-error main.tex 
  artifacts:
    paths: 
      - main.pdf  

pages:
  stage: deploy
  script:
    - mkdir public 
    - cp main.pdf public 
  artifacts:
    paths: 
      - public 
  only: 
    - master  