on: [push]

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: LaTeX-to-PDF github action
    steps:
    - name: Compilation
      uses: forkbabu/AutoEdit@v2.0
      with:
        tex_path: 'main.tex'
        push: 'yes'

