name: LateX to PDF

on:
  push:
    branches: 
      - master
      - dev
    tags:
       - '*'
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    container: andrzejolender/resume-cv:1.0.0
    runs-on: ubuntu-latest
    steps:
      - name: Compile Latex to PDF
        run: pdflatex -interaction=batchmode main.tex 2>/dev/null || exit 0
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output/AndrzejOlender.pdf
