on: [push]

jobs:
  latex-job:
    runs-on: andrzejolender/resume-cv
    name: A job to Compile Latex file
    steps:
    - uses: actions/checkout@v1
    - name: Compilation
      uses: vinay0410/tectonic-action@master
      with:
        tex_path: 'main.tex'
        push: 'yes'
